default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mike
  password: password
  host: localhost

development:
  <<: *default
  database: zipper_development

test:
  <<: *default
  database: zipper_test
